import { useState, useEffect } from 'react';

import Head from 'next/head'
import Image from 'next/image'

import { withAuthenticator } from '@aws-amplify/ui-react';
import { Amplify, Auth } from 'aws-amplify';
import '@aws-amplify/ui-react/styles.css';
import styles from '../styles/Home.module.css'
import awsExports from '../src/aws-exports';
Amplify.configure(awsExports);


// Auth.currentAuthenticatedUser({
//     bypassCache: false  // Optional, By default is false. If set to true, this call will send a request to Cognito to get the latest user data
// }).then(user => console.log(JSON.stringify(user, null, 4)))
// .catch(err => console.log(err));

function Home(signOut, user) {
  // const str = JSON.stringify(user, null, 4); // (Optional) beautiful indented output.
  // console.log(str);
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Add Bootstrap Navigation Bar for Testing */}
        <nav
          className="navbar navbar-dark bg-dark"
          aria-label="First navbar example"
        >
          <div className="container-fluid">
            <a className="navbar-brand" href="#">
              Test Application
            </a>
            <button
              className="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarsExample01"
              aria-controls="navbarsExample01"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span className="navbar-toggler-icon"></span>
            </button>

            <div className="collapse navbar-collapse" id="navbarsExample01">
              <ul className="navbar-nav me-auto mb-2">
                <li className="nav-item">
                  <a className="nav-link active" aria-current="page" href="#">
                    Home
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="#">
                    About
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </main>
      <hr className="bg-primary border-2 border-top border-primary"></hr>
      <WorkspacesStarter/>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


function InitializeApp(user) {
  function handleClick(event){
   console.log() 
  }

  return (
    <div className="container">
      <div className="d-flex justify-content-center">  
        <button onClick={handleClick}>Initialize Account</button>
      </div>
    </div>
    );
}


const WorkspaceMain = ({workspace}) => {
  console.log(workspace.labelbox_aws_account)
  return (
    <div className="container-fluid">
      <h2>Workspace</h2>

      <div className="container-fluid">
      <div className="row mt-3">
          <div className="col-md-auto">
            <label htmlFor="exampleFormControlInput1" className="form-label">Labelbox AWS Account</label>               
          </div>
          <div className="col-md-auto">
            <input type="email" className="form-control" id="exampleFormControlInput1" value={workspace.labelbox_aws_account} readOnly={false}/>
          </div>
        </div>
      
      <div className="row mt-3">
          <div className="col-md-auto">
            <label htmlFor="exampleFormControlInput1" className="form-label">Labelbox External ID</label>          
          </div>
          <div className="col-md-auto">
            <input type="email" className="form-control" id="exampleFormControlInput1" value={workspace.labelbox_external_id} readOnly={false}/>
          </div>
        </div>

        <div className="row mt-3">
          <div className="col-md-auto">
            <h3>Start Labeling</h3>
          </div>
          <div className="col-md-auto">
            <a className="btn btn-primary" href="https://app.labelbox.com/signin" target="_blank" rel="noreferrer" >Labelbox</a>
          </div>
        </div>

          <div className="row mt-3">
          <div className="col-md-auto">
            <h3>Create Training Job</h3>
          </div>
          <div className="col-md-auto">
            <button className="btn btn-secondary" type="submit">Train</button>
          </div>
          </div>
          <div className="row mt-3">
          <div className="col-md-auto">
          <h3>Model Assisted Labeling</h3>
          </div>
          <div className="col-md-auto">
          <button className="btn btn-primary" type="submit">Label Remaining Data</button>
          </div>
        </div>
      </div>
      </div>
  )
}


const Datasets = () => {
  return (
    <div className="container-fluid">
      <h2>Datasets</h2>
      <table className="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>@mdo</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>@fat</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td colSpan="2">Larry the Bird</td>
            <td>@twitter</td>
          </tr>
        </tbody>
      </table>
    </div>
  )
}


const Models = () => {
  return (
    <div className="container-fluid">
      <h2>Models</h2>
      <table className="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>@mdo</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>@fat</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td colSpan="2">Larry the Bird</td>
            <td>@twitter</td>
          </tr>
        </tbody>
      </table>
    </div>
  )
}


const WorkspaceUI = ({workspace}) => {
  console.log(workspace)
  return (
    <div>
      <PrimaryNav workspace={workspace}/>
    </div>
  )
}


const PrimaryNav = ({workspace}) =>{
  return (
    <div className="container">
    <ul className="nav nav-pills mb-3" id="pills-tab" role="tablist">
      <li className="nav-item" role="presentation">
        <button className="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Workspace</button>
      </li>
      <li className="nav-item" role="presentation">
        <button className="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Datasets</button>
      </li>
      <li className="nav-item" role="presentation">
        <button className="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">Models</button>
      </li>
      <li className="nav-item" role="presentation">
        <button className="nav-link" id="pills-disabled-tab" data-bs-toggle="pill" data-bs-target="#pills-disabled" type="button" role="tab" aria-controls="pills-disabled" aria-selected="false">Settings</button>
      </li>
    </ul>

    <div className="tab-content" id="pills-tabContent">
      <div className="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabIndex="0">
        <WorkspaceMain workspace={workspace}/>
      </div>
      <div className="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" tabIndex="0">
        <Datasets workspace={workspace}/>
      </div>
      <div className="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab" tabIndex="0">
        <Models workspace={workspace}/>
      </div>
      <div className="tab-pane fade" id="pills-disabled" role="tabpanel" aria-labelledby="pills-disabled-tab" tabIndex="0">...</div>
    </div>
      
    </div>
  )
}


const MockWorkspaces = [
  {id: "000001",
  owner_id: 'jnsfjnsfdn',
  name: 'mock-workspace',
  labelbox_aws_account: '098240980394',
  labelbox_external_id: '0920djdn09123n'
}]


const WorkspacesStarter = (user) => {
  const [workspaces, setWorkspaces] = useState([]);
  const [initialized, setInitialized] = useState(false);
  useEffect(() => {
    if (!initialized) {
      console.log('initializing Workspace')
      setTimeout(() => {
        setWorkspaces(MockWorkspaces)
        setInitialized(true)
      
      }, 5000)
    }
  }
  );
  console.log(initialized)
  return (
    <div>
      {initialized  
      // The workspace is hard coded, i.e, we take the first one
      ? <WorkspaceUI workspace={workspaces[0]}/>
      : <div>
          <div className="spinner-border text-primary" role="status">
          </div>
          <span >Initializing Workspace...</span>
        </div>
    }

    </div>
  )
}


export default withAuthenticator(Home);
// export default Home;
