import os.path
from pathlib import Path

TERRAFORM_PATH = Path(__file__).parent.parent.joinpath('infrastructure')
PARAMETERS_PATH = TERRAFORM_PATH.joinpath('parameters.tfvars')

def save_terraform_vars(vars, path):
    with open(path, 'w') as f:
        f.write("""# DO NOT USE THIS FILE\n# PARAMETERS HERE ARE GENERATED BY APPLICATION ONLY\n""")
        for key, value in vars.items():
            line = f"{key} = \"{value}\"\n"
            f.write(line)




def build_terraform_command(vars, params_path=PARAMETERS_PATH, output_name='output'):
    save_terraform_vars(vars, params_path)
    path = os.path.abspath(params_path)
    cmd = f"terraform plan -out {output_name} -var-file {path}"

    return cmd



vars = {'s3_bucket_name': {"a": 1},
        'profile': 'd4data'}

cmd = build_terraform_command(vars)
print(cmd)